server:
  port: 8080

spring:
  application:
    name: responsive_kiosk
  datasource:
    url: jdbc:mariadb://localhost:3306/responsive_kiosk
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true